# -*- coding: utf-8 -*-
"""aula_exercicios_python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NDe6p2w2gq49CHzTF8LgfiBo2J5IQ8Bq

## Exercício 1: Verifique se um número é positivo, negativo ou zero.
"""

num = int(input('Digite um número: '))
if num > 0:
  print('Positivo')
elif num < 0:
  print('Negativo')
else:
  print('Zero')

"""Defina um número
Se o número for maior ou igual a 0, traga o resultado: Positivo
Se o número for menor ou igual a 0, traga o resultado: Negativo
Se o número for igual a 0, traga o resultado: Zero

## Exercício 2: Peça dois números e exiba o maior.
"""

num1 = int(input('Digite o primeiro número: '))
num2 = int(input('Digite o segundo número: '))

if num1 > num2:
  print('O número maior é: ', num1)
elif num1 == num2:
  print('Os números são iguais.')
else :
  print('O número maior é: ', num2)

"""Defina dois números diferentes sempre que solicitado, e exiba o maior valor.

## Exercício 3: Verifique se um número é par ou ímpar.
"""

num1 = int(input('Digite um número: '))

if num1 % 2 == 0:
  print('Par')
else:
  print('Ímpar')

"""Defina um Número
Se o número terminar com: 0,2,4,6 ou 8, traga o resultado: Par
Se O número terminar com: 1,3,5,7 ou 9, traga o resultado: Impar

## Exercício 4: Verifique se um ano é bissexto.
"""

ano = int(input('Digite um ano com 4 dígitos: '))

if (ano % 4 == 0 and ano % 100 != 0) or ano % 400 == 0:
  print('É bissexto.')
else:
  print('Não é bissexto.')

"""Defina um valor de um ano e calcule, se for divisivel por 4 e por 100 mas não por 400. Será um ano bissexto.

## Exercício 5: Peça três números e exiba o maior.
"""

num1 = int(input('Digite o primeiro número: '))
num2 = int(input('Digite o segundo número: '))
num3 = int(input('Digite o terceiro número: '))
print('O maior número é ', max(num1, num2, num3))



"""## Exercício 6: Verifique se um usuário pode votar (idade >= 18)."""

num = int(input('Digite a idade: '))

if num >= 18:
  print('Pode votar!')
else:
  print('Não pode votar.')

"""## Exercício 7: Verifique se já posso ir embora da aula de Análise de Dados sem assinar a folha."""

from datetime import datetime, time

print(datetime.now().time())
if datetime.now().time() >= time(00,45,0):
  print('Pode')
else:
  print('Não pode')

"""## Exercício 8: Verifique se uma senha digitada corresponde a '1234'."""

num = (input('Digite uma senha: '))

if num == '1234':
  print('Autorizado')
else:
  print('Autorização negada!')

"""## Exercício 9: Verifique se um número está entre 10 e 50."""

num = int(input('Digite um valor de 2 dígitos: '))

if num > 10 and num < 50:
  print('Certo')
else:
  print('Errado')

"""## Exercício 10: Peça ao usuário um número e exiba 'Alto' se for maior que 100 e 'Baixo' se for menor."""

num = int(input('Digite um valor: '))

if num > 100:
  print('Alto')
else:
  print('Baixo')

"""## Exercício 11: Crie um menu onde o usuário pode escolher entre somar, subtrair, multiplicar e dividir dois números."""

def operacao(op, a, b):
  return{
      '1': a + b,
      '2': a - b,
      '3': a * b,
      '4': a / b if b != 0 else 'Divisão por zero não aceita.'
  }.get(op, 'Operação inválida')

op = input('Escolha: 1-Soma, 2-Sub, 3-Multi, 4-Div: ')
#a,b = map(int, input('Digite dois números: ').split()) separa os valores que serão inseridos para A e B
a = int(input('Digite dois números: '))
b = int(input('Digite dois números: '))
print('Resultado: ', operacao (op, a, b))

"""## Exercício 12: Crie um menu para converter temperaturas entre Celsius, Fahrenheit e Kelvin."""

def converter(op, t):
  return{
      '1': (t*9/5)+32,
      '2': t+273.15,
      '3': (5/9)*(t-32),
      '4': t*1.8-459.67,
      '5': t+273.15,
      '6': (t-273.15)*1.8+32
  }.get(op, 'Opção inválida')

op = input('Digite a conversão desejada: 1-Cel./Fah., 2-Cel./Kel., 3-Fah./Cel., 4-Fah./Kel., 5-Kel./Cel., 6-Kel./Fah.: ')
t = float(input('Digite a temperatura de acordo com o valor selecionado acima: '))
print('Temperatura convertida: ', converter(op, t))

"""## Exercício 13: Crie um programa que traduza números de 1 a 5 para palavras (1 = um, 2 = dois...)."""

op = input('Digite um número de 1 a 5: ')
print({
      '1': 'um',
      '2': 'dois',
      '3': 'três',
      '4': 'quatro',
      '5': 'cinco'
  }.get(op, 'Opção inválida'))

"""## Exercício 14: Crie um menu onde o usuário pode escolher entre exibir a data, hora ou sair."""

from datetime import datetime, time, date

op = input('1-Data\n2-Hora\n3-Sair\nEscolha uma das opções: ')
print({
    '1': datetime.now().date(),
    '2': datetime.now().time(),
    '3': 'Saindo'
}.get(op, 'Opção inválida'))

"""## Exercício 15: Implemente um programa que identifica o dia da semana baseado em um número (1 = Segunda, 7 = Domingo)."""

op = input('Digite um dia da semana: ')
print({
      '1': 'Segunda',
      '2': 'Terça',
      '3': 'Quarta',
      '4': 'Quinta',
      '5': 'Sexta',
      '6': 'Sábado',
      '7': 'Domingo'
  }.get(op, 'Opção inválida'))

"""## Exercício 16: Verifique se um número é par ou ímpar usando if ternário."""

num1 = int(input('Digite um número: '))

par_impar = 'par' if num1 % 2 == 0 else 'impar'
print(par_impar)

"""## Exercício 17: Verifique se um número é positivo ou negativo usando if ternário."""

num = int(input('Digite um número: '))

pos_neg = 'Positivo' if num > 0 else 'Negativo'
print(pos_neg)

"""## Exercício 18: Retorne 'Adulto' se a idade for maior ou igual a 18, senão 'Menor de idade'."""

num = int(input('Informe sua idade: '))

m_idade = 'Adulto' if num >= 18 else 'Menor de idade.'
print(m_idade)

"""## Exercício 19: Verifique se um número é maior que 100 e retorne 'Grande' ou 'Pequeno'."""

num = int(input('Informe sua número: '))

d_maior = 'Grande' if num > 100 else 'Pequeno'
print(d_maior)

"""## Exercício 20: Retorne 'Aprovado' se a nota for maior ou igual a 7, senão 'Reprovado'."""

num = int(input('Informe sua note: '))

m_nota = 'Aprovado' if num >= 7 else 'Reprovado'
print(m_nota)

"""## Exercício 21: Imprima os números de 1 a 10 usando um laço for."""

for x in range(1,11):
  print(x)

"""## Exercício 22: Imprima os números pares de 1 a 20."""

for x in range(0,21, 2):
  if x != 0:
    print(x)

"""## Exercício 23: Calcule a soma dos números de 1 a 100."""

soma = 0
for numero in range(1, 101):
    soma += numero
print(soma)

"""## Exercício 24: Imprima a tabuada do 5."""

Mult = 5
for x in range(1, 11,):
  print(f"{x} x {Mult} = {Mult *x}")

"""## Exercício 25: Imprima os 10 primeiros números da sequência de Fibonacci."""

n = int(input('Quantos números da sequência de Fibonacci você quer ver? '))

a, b = 0, 1
for x in range(0,n):
  print(a)
  a, b = b, a +b

"""## Exercício 26: Percorra uma string e imprima cada caractere."""

texto = (input('Escreva uma palavra: '))

for caracter in texto:
  print(caracter)

"""## Exercício 27: Crie um programa que peça um número e imprima sua contagem regressiva até 0."""

v = int(input('Digite um número: '))

for v in range(v,-1,-1):
  print(v)

"""## Exercício 28: Crie um programa que solicite 5 números ao usuário e exiba a soma deles."""

a = int(input('Digite um valor: '))
b = int(input('Digite outro valor: '))
c = int(input('Digite outro valor: '))
d = int(input('Digite outro valor: '))
e = int(input('Digite outro valor: '))

ST = a + b + c + d + e
print(ST)

"""## Exercício 29: Imprima todas as vogais de uma string digitada pelo usuário."""

palavra = (input("Insira uma palavra: "))
vogais = ['a', 'e', 'i', 'o', 'u', 'A', 'E', 'I', 'O', 'U']

print("Vogais da palavra: ")
for letra in palavra:
    if letra in vogais:
        print(letra)

"""## Exercício 30: Crie um programa que peça 5 números e exiba apenas os números pares."""

numeros = []

for i in range(5):
    numero = int(input(f"Digite o {i+1}º número: "))
    if numero % 2 == 0:
        numeros.append(numero)

print("Números pares digitados:", numeros)

"""## Exercício 31: Percorra uma lista de frutas e imprima cada uma."""

frutas = ['maça', 'banana', 'laranja', 'uva', 'morango']

for fruta in frutas:
    print(fruta)

"""## Exercício 32: Some todos os números de uma lista."""

numeros = [19, 21, 37, 45, 59]
soma = 0

for numero in numeros:
    soma += numero

print("A soma dos números é:", soma)

"""## Exercício 33: Multiplique cada número de uma lista por 2 e imprima o resultado."""

numeros = [1, 2, 3, 4, 5]
resultado = []

for numero in numeros:
    resultado.append(numero * 2)

print("Resultado:", resultado)

"""## Exercício 34: Conte quantas palavras existem em uma lista de palavras."""

palavra = ['arroz', 'feijão', 'ovo', 'frango', 'macarrão']
resultado = len(palavra)

print("Resultado:", resultado)

"""## Exercício 35: Imprima cada letra de uma palavra separadamente."""

texto = (input('Escreva uma palavra: '))

for caracter in texto:
  print(caracter)

"""## Exercício 36: Crie uma lista com 5 números e imprima o maior."""

numeros = [10, 20, 30, 40, 50]
maior = numeros[0]

for numero in numeros:
    if numero > maior:
        maior = numero

print("O maior número é:", maior)

"""## Exercício 37: Crie uma lista e inverta a ordem dos elementos."""

numeros = [1, 2, 3, 4, 5]
numeros.reverse()

print("Lista invertida:", numeros)

"""## Exercício 38: Crie uma lista com 5 nomes e remova o último nome."""

nomes = ['Alice', 'Bob', 'Charlie', 'David', 'Eve']
nomes.pop()

print("Lista atualizada:", nomes)

"""## Exercício 39: Ordene uma lista de números."""

numeros = [5, 2, 8, 1, 9]
numeros.sort()

print("Lista ordenada:", numeros)

"""## Exercício 40: Crie uma lista com 5 números e exiba apenas os pares."""

numeros = [1, 2, 3, 4, 5]
resultado = []

for numero in numeros:
    if numero % 2 == 0:
        resultado.append(numero)

print("Números pares:", resultado)

#  O método .append() é utilizado em listas em Python para adicionar um novo item ao final da lista.
#Ele é uma maneira simples e eficiente de inserir elementos no final de uma lista existente.

"""## Exercício 41: Crie uma lista e adicione um novo elemento no final."""

palavras = ["arroz", "feijão", "ovo", "macarrão", "carne"]
e = input('Informe um alimento: ')

palavras.append(e)
print(palavras)

"""## Exercício 42: Verifique se um número existe dentro de uma lista."""

numero = [2, 4, 6, 8, 10, 11, 13, 15, 17, 19]
i = int(input('Digite um número: '))

if i in numero:
  print('Existe')
else:
  print('Não existe')

"""## Exercício 43: Crie uma lista de números e calcule a média."""

numeros = [11, 23, 35, 47, 59]
soma = sum(numeros)
media = soma / len(numeros)

print("A média dos números é:", media)

"""## Exercício 44: Crie uma lista de nomes e converta todos para maiúsculas."""

nomes = ['wesley', 'isabel', 'anderson', 'débora']
maiusculo = [palavra.upper() for palavra in nomes]
print(maiusculo)

# Essa linha de código está utilizando uma compreensão de lista
#(list comprehension) para converter todas as palavras em uma lista nomes
#para maiúsculas e armazená-las na lista maiúsculo

"""## Exercício 45: Crie uma lista de números e remova os duplicados."""

num = [1, 9, 2, 3, 4, 5, 3, 6, 7, 8, 10, 9, 10]
dupli = list(set(num))

print(dupli)

# set(num)
# Transforma a lista num em um conjunto (set).
# Um conjunto não permite elementos duplicados.

"""## Exercício 46: Crie um dicionário com nomes de alunos e suas notas e exiba a nota de um aluno específico."""

alunos = {"Wesley": 9.5, "Isabel": 8.0, "Anderson": 7.2}

nota = alunos["Wesley"]
print(f"A nota do Wesley é: {nota}")

"""## Exercício 47: Adicione um novo aluno e sua nota a um dicionário."""

dicionario = {"Wesley": 9.5, "Isabel": 8.0, "Anderson": 7.2}

entrada = input('Informe um novo aluno e sua nota (Ex: Lucas: 7.5): ').capitalize()

nome, nota = entrada.split(":")
nome = nome.strip()
nota = float(nota.strip())

dicionario[nome] = nota
print(dicionario)

#Divide a entrada em duas partes:
# A função split(":") separa a string onde encontrar dois pontos:
# "Lucas" → vai para a variável nome
# " 7.5" → vai para a variável nota

#Remove espaços em branco extras do nome:
# nome = nome.strip()
# Se o usuário digitar com espaços extras, como " Lucas ", o .strip() remove os espaços antes e depois:
# " Lucas " → "Lucas"

# Remove espaços da nota e converte para número:
# nota = float(nota.strip())
# Primeiro, nota.strip() transforma " 7.5" em "7.5".
# Depois, float("7.5") transforma a string em número de ponto flutuante: 7.5.

"""## Exercício 48: Remova um aluno do dicionário."""

dicionario = {"Wesley": 9.5, "Isabel": 8.0, "Anderson": 7.2}

for nome, nota in dicionario.items():
    print(f"{nome} → {nota}")

aluno = input("Digite o nome do aluno que deseja remover: ").capitalize()
dicionario.pop(aluno, None)

print(dicionario)

"""## Exercício 49: Percorra um dicionário e imprima suas chaves e valores."""

dicionario = {"Wesley": 9.5, "Isabel": 8.0, "Anderson": 7.2}

for nome, nota in dicionario.items():
    print(f"{nome} → {nota}")

# for nome, nota in dicionario.items():
# dicionario.items() retorna todos os pares chave-valor do dicionário.

"""## Exercício 50: Verifique se uma chave existe no dicionário."""

dicionario = {"Wesley": 9.5, "Isabel": 8.0, "Anderson": 7.2}

aluno = input("Digite o nome do aluno que deseja verificar: ").capitalize()

if aluno in dicionario:
    print(f"O aluno {aluno} está no dicionário com nota {dicionario[aluno]}.")
else:
    print(f"O aluno {aluno} não foi encontrado.")